apiVersion: v1
kind: Pod
metadata:
  name: labels
  labels:
    purpose: demo
    project: roboshop
  annotations:
    description: " this pod created to demo annotations"
spec:
  containers:
  - name: nginx
    image: nginx
